# Generated by Django 4.0.2 on 2022-02-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='picture',
            field=models.ImageField(upload_to='home/'),
        ),
    ]
